### ISSUE TITLE
The result of the sale does not appear at the end of the sale. [BUG]

### ISSUE THREAD

**Issue by ChrisTVH** [MackenzieMolloy/ShopGUIPlus-SellGUI#15]
### About the instance
- ShopGUIPlus-SellGUI: 1.1.8
- ShopGUIPlis: 1.98.1
- Purpur 1.21.1 Build 2308

### About the problem
- After using the sale GUI, at the end of the sale, the messages of how much you earned from the sale do not appear.
![image](https://github.com/user-attachments/assets/b0b09a77-afa6-49b6-aa39-7fdb21d973f4)

**Comment by MackenzieMolloy** [comment]
Please run _/sg dump_ and provide the link it generates here.

**Comment by ChrisTVH** [comment]
> Please run _/sg dump_ and provide the link it generates here.

https://paste.helpch.at/ezonuxacas

**Comment by MackenzieMolloy** [comment]
I've ran a test using your SellGUI config and default ShopGUIPlus configs - I cannot recreate the issue you're experiencing.
![image](https://github.com/user-attachments/assets/26b9bf77-ed4f-46de-91a2-119ac6e51c34)

So far to date, I've only ever had bug reports from people using Purpur (4 in total, including yours) and have never been able to recreate the bugs reported by those users. I can only deduce that Purpur is the issue.

I encourage you to switch to Paper or similar and see if the bug still occurs - I inform you that there are large servers (100+ concurrent players) running this plugin without issue so the issue is exclusively with your setup/configuration.

**Comment by ChrisTVH** [comment]
This happens more specifically when selling some objects on my server called fragments, which are custom objects with hex color and lore.

**Comment by MackenzieMolloy** [comment]
Are the custom items made via a plugin? If so, which plugin and can you provide the configs for the items?

**Comment by ChrisTVH** [comment]
> Are the custom items made via a plugin? If so, which plugin and can you provide the configs for the items?

I created it directly in shopgui+ and then bought it and left it only in sale mode, to avoid problems.
I will pass you the store that contains these objects.

[archeology.zip](https://github.com/user-attachments/files/17048999/archeology.zip)

**Comment by MackenzieMolloy** [comment]
I have bought an item from your config and sold it with SellGUI, I got no error:

![image](https://github.com/user-attachments/assets/3babd520-472d-4a22-baa1-1dabc67f78a4)

**Comment by ChrisTVH** [comment]
So if my software must be the problem.
